"""
Create a program that will play the “cows and bulls” game with the user.
The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place, they
have a “cow”. For every digit the user guessed correctly in the wrong place
is a “bull.” Every time the user makes a guess, tell them how many “cows” and
“bulls” they have. Once the user guesses the correct number, the game is over.
Keep track of the number of guesses the user makes throughout the game and tell
the user at the end.

Say the number generated by the computer is 1038. An example interaction could
look like this:
    Welcome to the Cows and Bulls Game!
    Enter a number:
    >>> 1234
    2 cows, 0 bulls
    >>> 1256
    1 cow, 1 bull
    ...
Until the user guesses the number.
"""

from random import randrange

answer = "{:04d}".format(randrange(9999))

print('Welcome to the Cows and Bulls Game!')

count, guess = 0, ''
while guess != answer:
    guess = input('Enter a number:')
    count += 1
    cows, bulls = 0, 0
    for i, v in enumerate(guess):
        if v == answer[i]:
            cows += 1
        elif v in answer:
            bulls += 1
    print('{} cow(s), {} bull(s)'.format(cows, bulls))
print('You\'ve Won! The answer was {}.'.format(answer))
